### PR TITLE
Change copyright year to current year - to fix #67

### LINKED ISSUE #67: Copyright notice on the website still at 2014
Title says all

### PR DESCRIPTION
**Pull request by ajburley**
A simple change to fix #67

### CODE REVIEW

**Comment by delroth** [comment]
Nobody really agrees on what copyright here should be (initial creation? current date? etc.). I'm using creation here.

**Comment by orbea** [comment]
@delroth I don't really care, but generally copyright dates should be a range to most useful.

For example `2014-2018` would be what I would expect if the site was created in `2014` and maintained until the current year of `2018`. If any years had no changes like say `2015` it could be represented like, `2014, 2016-2018`. This is how its generally done with software and package management at least.

**Comment by delroth** [comment]
Yes but they don't have to be useful, they provide no value, and frankly I should just remove this copyright header altogether because other than generating noise I'm not sure what it's doing.

**Comment by JosJuice** [comment]
+1 for removing the date or the whole copyright notice.

**Pull request closed without merging**
