### PR TITLE
css: support anchors on <h2> and <h4> headers

### PR DESCRIPTION
**Pull request by Tilka**

### CODE REVIEW

**Comment by Tilka** [comment]
@Parlane: This is a PR for merging into master. The commit by delroth is from the stable branch which for some reason is further ahead.

**Comment by delroth** [comment]
Put that directly on stable. I use master for experiments.

**Comment by delroth** [comment]
Cherry-picked it directly.

**Comment by delroth** [comment]
(And should be live.)

**Comment by Parlane** [comment]
Thanks @delroth

**Pull request closed without merging**
